default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['MAX_THREADS'] || 10 %>
  username: <%= ENV['DATABASE_USERNAME']%>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default